"""add exam_type to subject

Revision ID: 0fca6566851e
Revises: 62bccee57a4c
Create Date: 2025-01-14 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0fca6566851e'
down_revision: Union[str, None] = '62bccee57a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add exam_type column with default empty JSON array
    op.add_column('subject', sa.Column('exam_type', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'exam_type')
    # ### end Alembic commands ###

