"""minor fix in base question schema

Revision ID: 13d234b6fc26
Revises: c7a69134c9a6
Create Date: 2025-12-04 16:47:18.524014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '13d234b6fc26'
down_revision: Union[str, None] = 'c7a69134c9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('topic_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_constraint('question_chapter_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'topic', ['topic_id'], ['id'])
    op.drop_column('question', 'chapter_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_chapter_id_fkey', 'question', 'chapter', ['chapter_id'], ['id'])
    op.drop_column('question', 'topic_id')
    # ### end Alembic commands ###
