"""contest leaderboard combined with analytics

Revision ID: 2530388b5d58
Revises: 55cfedbb76ca
Create Date: 2025-12-20 12:50:36.974735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '2530388b5d58'
down_revision: Union[str, None] = '55cfedbb76ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contestsubmissionanalytics')
    op.add_column('contestleaderboard', sa.Column('accuracy', sa.Float(), nullable=False))
    op.add_column('contestleaderboard', sa.Column('total_questions', sa.Integer(), nullable=False))
    op.add_column('contestleaderboard', sa.Column('attempted', sa.Integer(), nullable=False))
    op.add_column('contestleaderboard', sa.Column('unattempted', sa.Integer(), nullable=False))
    op.add_column('contestleaderboard', sa.Column('correct', sa.Integer(), nullable=False))
    op.add_column('contestleaderboard', sa.Column('incorrect', sa.Integer(), nullable=False))
    op.add_column('contestleaderboard', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('contestleaderboard', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_foreign_key(None, 'contestleaderboard', 'contest', ['contest_id'], ['id'])
    op.create_foreign_key(None, 'contestleaderboard', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contestleaderboard', type_='foreignkey')
    op.drop_constraint(None, 'contestleaderboard', type_='foreignkey')
    op.alter_column('contestleaderboard', 'score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('contestleaderboard', 'created_at')
    op.drop_column('contestleaderboard', 'incorrect')
    op.drop_column('contestleaderboard', 'correct')
    op.drop_column('contestleaderboard', 'unattempted')
    op.drop_column('contestleaderboard', 'attempted')
    op.drop_column('contestleaderboard', 'total_questions')
    op.drop_column('contestleaderboard', 'accuracy')
    op.create_table('contestsubmissionanalytics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('contest_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attempted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unattempted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correct', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('incorrect', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], name='contestsubmissionanalytics_contest_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='contestsubmissionanalytics_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contestsubmissionanalytics_pkey')
    )
    # ### end Alembic commands ###
