"""notes schema added

Revision ID: 29a83ad0ece9
Revises: g2b3c4d5e6f7
Create Date: 2025-12-29 16:32:35.667459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '29a83ad0ece9'
down_revision: Union[str, None] = 'g2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

notificationtype_enum = sa.Enum('INFO', 'SUCCESS', 'WARNING', 'CONTEST', 'ACHIEVEMENT', 'STREAK', 'SYSTEM', 'ANNOUNCEMENT', name='notificationtype')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    notificationtype_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('notes',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('chapter_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('web_view_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('web_content_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_chapter_id'), 'notes', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_notes_is_active'), 'notes', ['is_active'], unique=False)
    op.create_index(op.f('ix_notes_subject_id'), 'notes', ['subject_id'], unique=False)
    op.create_table('treasures',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('chapter_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treasures_chapter_id'), 'treasures', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_treasures_is_active'), 'treasures', ['is_active'], unique=False)
    op.create_index(op.f('ix_treasures_subject_id'), 'treasures', ['subject_id'], unique=False)
    op.alter_column('bookmarked_videos', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('bookmarked_videos', 'youtube_video_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    
    op.alter_column(
    'notifications',
    'type',
    server_default=None
    )
    op.alter_column(
        'notifications',
        'type',
        existing_type=sa.VARCHAR(length=50),
        type_=notificationtype_enum,
        existing_nullable=False,
        postgresql_using="type::notificationtype",
        server_default=sa.text("'INFO'::notificationtype")
    )

    op.alter_column('notifications', 'data',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_column('users', 'is_psychometric_completed')
    op.drop_column('users', 'class_grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('class_grade', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_psychometric_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('notifications', 'data',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('INFO', 'SUCCESS', 'WARNING', 'CONTEST', 'ACHIEVEMENT', 'STREAK', 'SYSTEM', 'ANNOUNCEMENT', name='notificationtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'info'::character varying"))
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bookmarked_videos', 'youtube_video_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bookmarked_videos', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_treasures_subject_id'), table_name='treasures')
    op.drop_index(op.f('ix_treasures_is_active'), table_name='treasures')
    op.drop_index(op.f('ix_treasures_chapter_id'), table_name='treasures')
    op.drop_table('treasures')
    op.drop_index(op.f('ix_notes_subject_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_is_active'), table_name='notes')
    op.drop_index(op.f('ix_notes_chapter_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
