"""user schema changed a bit

Revision ID: 32991d02a8a5
Revises: e54d602220c1
Create Date: 2025-12-22 02:00:39.930902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '32991d02a8a5'
down_revision: Union[str, None] = 'e54d602220c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('class_id', sqlmodel.sql.sqltypes.GUID(), server_default=text("'b85e3fc4-41b6-4237-b7b7-0a065d5a1887'")))
    op.create_index(op.f('ix_users_class_id'), 'users', ['class_id'], unique=False)
    op.create_foreign_key(None, 'users', 'class', ['class_id'], ['id'])
    op.drop_column('users', 'class_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('class_level', postgresql.ENUM('CLASS_9', 'CLASS_10', 'CLASS_11', 'CLASS_12', 'DROPPER', name='classlevel'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_class_id'), table_name='users')
    op.drop_column('users', 'class_id')
    # ### end Alembic commands ###
