"""badge schema updated

Revision ID: 36cda8b7ee71
Revises: ca18f54541fb
Create Date: 2025-12-08 18:33:17.738829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '36cda8b7ee71'
down_revision: Union[str, None] = 'ca18f54541fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('STREAK', 'PRACTICE_ARENA', name='badgecategory'), nullable=False),
    sa.Column('badge_type', sa.Enum('QUESTIONS_SOLVED', 'ACCURACY', 'DIFFICULTY_MASTER', 'STREAK', 'PERFECT_SCORE', 'SPEED_DEMON', 'CONSISTENCY', 'SUBJECT_MASTER', 'WEEKLY_CHALLENGE', 'MONTHLY_CHALLENGE', name='badgetype'), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY', name='badgerarity'), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon_svg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requirement_value', sa.Integer(), nullable=True),
    sa.Column('requirement_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points_reward', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_badge_type'), 'badges', ['badge_type'], unique=False)
    op.create_index(op.f('ix_badges_category'), 'badges', ['category'], unique=False)
    op.create_index(op.f('ix_badges_is_active'), 'badges', ['is_active'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('badge_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('is_earned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_user_badges_earned_at'), 'user_badges', ['earned_at'], unique=False)
    op.create_index(op.f('ix_user_badges_is_earned'), 'user_badges', ['is_earned'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_is_earned'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_earned_at'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_badges_is_active'), table_name='badges')
    op.drop_index(op.f('ix_badges_category'), table_name='badges')
    op.drop_index(op.f('ix_badges_badge_type'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
