"""minor fix in schema

Revision ID: 3731219cfe79
Revises: 86c7206d5b07
Create Date: 2025-12-23 15:47:26.539108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3731219cfe79'
down_revision: Union[str, None] = '86c7206d5b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_study_stats', 'performance_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_study_stats', sa.Column('performance_rating', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
