"""qotd schema added

Revision ID: 4762d8b7e524
Revises: 29a83ad0ece9
Create Date: 2025-12-30 15:52:10.007419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4762d8b7e524'
down_revision: Union[str, None] = '29a83ad0ece9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qotd',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('class_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qotd_class_id'), 'qotd', ['class_id'], unique=False)
    op.create_index(op.f('ix_qotd_created_at'), 'qotd', ['created_at'], unique=False)
    op.create_table('user_badges',
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('badge_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('is_seen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'badge_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_qotd_created_at'), table_name='qotd')
    op.drop_index(op.f('ix_qotd_class_id'), table_name='qotd')
    op.drop_table('qotd')
    # ### end Alembic commands ###
