"""minor fix in pyq schema

Revision ID: 51d5c6604dd0
Revises: 13d234b6fc26
Create Date: 2025-12-04 18:40:27.985241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d5c6604dd0'
down_revision: Union[str, None] = '13d234b6fc26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_previous_year_problems_user_id', table_name='previous_year_problems')
    op.drop_constraint('previous_year_problems_user_id_fkey', 'previous_year_problems', type_='foreignkey')
    op.drop_column('previous_year_problems', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('previous_year_problems', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('previous_year_problems_user_id_fkey', 'previous_year_problems', 'users', ['user_id'], ['id'])
    op.create_index('ix_previous_year_problems_user_id', 'previous_year_problems', ['user_id'], unique=False)
    # ### end Alembic commands ###
