"""minor fixed in the user shchema

Revision ID: 55cfedbb76ca
Revises: 7d79d91757c2
Create Date: 2025-12-17 01:32:59.132516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '55cfedbb76ca'
down_revision: Union[str, None] = '7d79d91757c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('school', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('users', 'avatar_svg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_svg', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'email')
    op.drop_column('users', 'city')
    op.drop_column('users', 'state')
    op.drop_column('users', 'school')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
