"""contest base schema created

Revision ID: 623038470b21
Revises: e2b6d4921897
Create Date: 2025-12-06 16:35:56.457825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '623038470b21'
down_revision: Union[str, None] = 'e2b6d4921897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('total_time', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'finished', 'not_started', name='conteststatus'), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contestleaderboard',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('contest_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('rating_before', sa.Integer(), nullable=False),
    sa.Column('rating_after', sa.Integer(), nullable=False),
    sa.Column('rating_delta', sa.Integer(), nullable=False),
    sa.Column('missed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contestsubmissionanalytics',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('contest_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('attempted', sa.Integer(), nullable=False),
    sa.Column('unattempted', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('incorrect', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contestquestions',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('contest_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contestquestions_contest_id'), 'contestquestions', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contestquestions_question_id'), 'contestquestions', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contestquestions_question_id'), table_name='contestquestions')
    op.drop_index(op.f('ix_contestquestions_contest_id'), table_name='contestquestions')
    op.drop_table('contestquestions')
    op.drop_table('contestsubmissionanalytics')
    op.drop_table('contestleaderboard')
    op.drop_table('contest')
    # ### end Alembic commands ###
