"""year field added in the pyq

Revision ID: 62bccee57a4c
Revises: b97bef5cc5e1
Create Date: 2025-12-13 01:08:46.875780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bccee57a4c'
down_revision: Union[str, None] = 'b97bef5cc5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('previous_year_problems', sa.Column('year', sa.Integer(), server_default="2016", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('previous_year_problems', 'year')
    # ### end Alembic commands ###
