"""fixes in the schema and schoalrship model aded

Revision ID: 6f7826d15bdb
Revises: d7b276c24f65
Create Date: 2026-01-03 00:40:30.773990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '6f7826d15bdb'
down_revision: Union[str, None] = 'd7b276c24f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

AttemptStatusEnum = ENUM(
    'active',
    'finished',
    'not_started',
    name='attemptstatus',
    create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarship',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('class_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('exam_type', sa.Enum('JEE_ADVANCED', 'JEE_MAINS', 'NEET', 'OLYMPIAD', 'CBSE', name='targetexam'), nullable=False),
    sa.Column('time_assigned', sa.Integer(), nullable=False),
    sa.Column('status',  AttemptStatusEnum, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_scholarship_user_id')
    )
    op.create_index(op.f('ix_scholarship_class_id'), 'scholarship', ['class_id'], unique=False)
    op.create_index(op.f('ix_scholarship_exam_type'), 'scholarship', ['exam_type'], unique=False)
    op.create_index(op.f('ix_scholarship_user_id'), 'scholarship', ['user_id'], unique=True)
    op.create_table('scholarship_results',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('scholarship_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('time_taken', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('incorrect', sa.Integer(), nullable=False),
    sa.Column('unattempted', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarship_results_scholarship_id'), 'scholarship_results', ['scholarship_id'], unique=False)
    op.create_index(op.f('ix_scholarship_results_submitted_at'), 'scholarship_results', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_scholarship_results_user_id'), 'scholarship_results', ['user_id'], unique=False)
    op.create_table('scholarshipquestion',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('scholarship_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarshipquestion_question_id'), 'scholarshipquestion', ['question_id'], unique=False)
    op.create_index(op.f('ix_scholarshipquestion_scholarship_id'), 'scholarshipquestion', ['scholarship_id'], unique=False)
    op.drop_index('ix_badges_created_at', table_name='badges')
    op.drop_index('ix_badges_is_active_created_at', table_name='badges')
    op.drop_index('ix_contest_ends_at', table_name='contest')
    op.drop_index('ix_contest_starts_at', table_name='contest')
    op.drop_column('contest', 'isScholarship')
    op.drop_index('ix_contestleaderboard_contest_id_user_id', table_name='contestleaderboard')
    op.drop_index('ix_contestleaderboard_rating_after', table_name='contestleaderboard')
    op.drop_index('ix_contestleaderboard_rating_delta', table_name='contestleaderboard')
    op.drop_index('ix_contestleaderboard_score', table_name='contestleaderboard')
    op.drop_index('ix_contestleaderboard_total_time', table_name='contestleaderboard')
    op.drop_index('ix_questionattempt_user_id_is_correct', table_name='question_attempts')
    op.drop_index('ix_user_badges_user_id_badge_id', table_name='user_badges')
    op.drop_index('ix_user_class_id', table_name='users')
    op.drop_index('ix_user_class_id_is_active', table_name='users')
    op.drop_index('ix_user_current_rating', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_current_rating', 'users', ['current_rating'], unique=False)
    op.create_index('ix_user_class_id_is_active', 'users', ['class_id', 'is_active'], unique=False)
    op.create_index('ix_user_class_id', 'users', ['class_id'], unique=False)
    op.create_index('ix_user_badges_user_id_badge_id', 'user_badges', ['user_id', 'badge_id'], unique=False)
    op.create_index('ix_questionattempt_user_id_is_correct', 'question_attempts', ['user_id', 'is_correct'], unique=False)
    op.create_index('ix_contestleaderboard_total_time', 'contestleaderboard', ['total_time'], unique=False)
    op.create_index('ix_contestleaderboard_score', 'contestleaderboard', ['score'], unique=False)
    op.create_index('ix_contestleaderboard_rating_delta', 'contestleaderboard', ['rating_delta'], unique=False)
    op.create_index('ix_contestleaderboard_rating_after', 'contestleaderboard', ['rating_after'], unique=False)
    op.create_index('ix_contestleaderboard_contest_id_user_id', 'contestleaderboard', ['contest_id', 'user_id'], unique=False)
    op.add_column('contest', sa.Column('isScholarship', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index('ix_contest_starts_at', 'contest', ['starts_at'], unique=False)
    op.create_index('ix_contest_ends_at', 'contest', ['ends_at'], unique=False)
    op.create_index('ix_badges_is_active_created_at', 'badges', ['is_active', 'created_at'], unique=False)
    op.create_index('ix_badges_created_at', 'badges', ['created_at'], unique=False)
    op.drop_index(op.f('ix_scholarshipquestion_scholarship_id'), table_name='scholarshipquestion')
    op.drop_index(op.f('ix_scholarshipquestion_question_id'), table_name='scholarshipquestion')
    op.drop_table('scholarshipquestion')
    op.drop_index(op.f('ix_scholarship_results_user_id'), table_name='scholarship_results')
    op.drop_index(op.f('ix_scholarship_results_submitted_at'), table_name='scholarship_results')
    op.drop_index(op.f('ix_scholarship_results_scholarship_id'), table_name='scholarship_results')
    op.drop_table('scholarship_results')
    op.drop_index(op.f('ix_scholarship_user_id'), table_name='scholarship')
    op.drop_index(op.f('ix_scholarship_exam_type'), table_name='scholarship')
    op.drop_index(op.f('ix_scholarship_class_id'), table_name='scholarship')
    op.drop_table('scholarship')
    # ### end Alembic commands ###
