"""doubt forum schema generate succesfully

Revision ID: 75de33638e92
Revises: 2530388b5d58
Create Date: 2025-12-21 23:10:24.155237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '75de33638e92'
down_revision: Union[str, None] = '2530388b5d58'
branch_labels: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doubt_posts',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('class_level', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_solved', sa.Boolean(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_level'], ['class.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doubt_posts_class_level'), 'doubt_posts', ['class_level'], unique=False)
    op.create_index(op.f('ix_doubt_posts_created_at'), 'doubt_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_doubt_posts_is_solved'), 'doubt_posts', ['is_solved'], unique=False)
    op.create_index(op.f('ix_doubt_posts_user_id'), 'doubt_posts', ['user_id'], unique=False)
    op.create_table('doubt_bookmarks',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['doubt_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doubt_bookmarks_created_at'), 'doubt_bookmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_doubt_bookmarks_post_id'), 'doubt_bookmarks', ['post_id'], unique=False)
    op.create_index(op.f('ix_doubt_bookmarks_user_id'), 'doubt_bookmarks', ['user_id'], unique=False)
    op.create_table('doubt_comments',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['doubt_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doubt_comments_created_at'), 'doubt_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_doubt_comments_post_id'), 'doubt_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_doubt_comments_user_id'), 'doubt_comments', ['user_id'], unique=False)
    op.add_column('contest', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('contest', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'description')
    op.drop_column('contest', 'name')
    op.drop_index(op.f('ix_doubt_comments_user_id'), table_name='doubt_comments')
    op.drop_index(op.f('ix_doubt_comments_post_id'), table_name='doubt_comments')
    op.drop_index(op.f('ix_doubt_comments_created_at'), table_name='doubt_comments')
    op.drop_table('doubt_comments')
    op.drop_index(op.f('ix_doubt_bookmarks_user_id'), table_name='doubt_bookmarks')
    op.drop_index(op.f('ix_doubt_bookmarks_post_id'), table_name='doubt_bookmarks')
    op.drop_index(op.f('ix_doubt_bookmarks_created_at'), table_name='doubt_bookmarks')
    op.drop_table('doubt_bookmarks')
    op.drop_index(op.f('ix_doubt_posts_user_id'), table_name='doubt_posts')
    op.drop_index(op.f('ix_doubt_posts_is_solved'), table_name='doubt_posts')
    op.drop_index(op.f('ix_doubt_posts_created_at'), table_name='doubt_posts')
    op.drop_index(op.f('ix_doubt_posts_class_level'), table_name='doubt_posts')
    op.drop_table('doubt_posts')
    # ### end Alembic commands ###
