"""add performance indexes for ranking

Revision ID: 765633b05342
Revises: f92f03a18586
Create Date: 2025-01-15 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '765633b05342'
down_revision: Union[str, None] = 'f92f03a18586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Indexes for contest leaderboard queries
    op.create_index(
        'ix_contestleaderboard_contest_id_user_id',
        'contestleaderboard',
        ['contest_id', 'user_id'],
        unique=False
    )
    op.create_index(
        'ix_contestleaderboard_rating_after',
        'contestleaderboard',
        ['rating_after'],
        unique=False
    )
    op.create_index(
        'ix_contestleaderboard_rating_delta',
        'contestleaderboard',
        ['rating_delta'],
        unique=False
    )
    op.create_index(
        'ix_contestleaderboard_score',
        'contestleaderboard',
        ['score'],
        unique=False
    )
    op.create_index(
        'ix_contestleaderboard_total_time',
        'contestleaderboard',
        ['total_time'],
        unique=False
    )
    
    # Indexes for contest queries
    op.create_index(
        'ix_contest_ends_at',
        'contest',
        ['ends_at'],
        unique=False
    )
    op.create_index(
        'ix_contest_starts_at',
        'contest',
        ['starts_at'],
        unique=False
    )

    # Indexes for user queries
    op.create_index(
        'ix_user_class_id',
        'users',
        ['class_id'],
        unique=False
    )

    op.create_index(
        'ix_user_current_rating',
        'users',
        ['current_rating'],
        unique=False
    )
    op.create_index(
        'ix_user_class_id_is_active',
        'users',
        ['class_id', 'is_active'],
        unique=False
    )
    
    # Indexes for question attempts (arena ranking)
    op.create_index(
        'ix_questionattempt_user_id_is_correct',
        'question_attempts',
        ['user_id', 'is_correct'],
        unique=False
    )

    op.create_index(
        'ix_questionattempt_user_id_created_at',
        'question_attempts',
        ['user_id', 'created_at'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_questionattempt_user_id_created_at', table_name='question_attempts')
    op.drop_index('ix_questionattempt_user_id_is_correct', table_name='question_attempts')
    op.drop_index('ix_user_class_id_is_active', table_name='users')
    op.drop_index('ix_user_current_rating', table_name='users')
    op.drop_index('ix_user_class_id', table_name='users')
    op.drop_index('ix_contest_starts_at', table_name='contest')
    op.drop_index('ix_contest_ends_at', table_name='contest')
    op.drop_index('ix_contestleaderboard_total_time', table_name='contestleaderboard')
    op.drop_index('ix_contestleaderboard_score', table_name='contestleaderboard')
    op.drop_index('ix_contestleaderboard_rating_delta', table_name='contestleaderboard')
    op.drop_index('ix_contestleaderboard_rating_after', table_name='contestleaderboard')
    op.drop_index('ix_contestleaderboard_contest_id_user_id', table_name='contestleaderboard')
    # ### end Alembic commands ###

