"""weak topics added

Revision ID: 7d79d91757c2
Revises: 83f9130f3482
Create Date: 2025-12-16 19:39:56.139928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7d79d91757c2'
down_revision: Union[str, None] = '83f9130f3482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_weak_topics',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('topic_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('total_attempt', sa.Integer(), nullable=False),
    sa.Column('incorrect_attempts', sa.Integer(), nullable=False),
    sa.Column('correct_attempts', sa.Integer(), nullable=False),
    sa.Column('weakness_score', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_topic')
    )
    op.create_index('idx_user_weakness', 'user_weak_topics', ['user_id', 'weakness_score'], unique=False)
    op.create_index(op.f('ix_user_weak_topics_last_updated'), 'user_weak_topics', ['last_updated'], unique=False)
    op.create_index(op.f('ix_user_weak_topics_topic_id'), 'user_weak_topics', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_weak_topics_user_id'), 'user_weak_topics', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_weak_topics_weakness_score'), 'user_weak_topics', ['weakness_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_weak_topics_weakness_score'), table_name='user_weak_topics')
    op.drop_index(op.f('ix_user_weak_topics_user_id'), table_name='user_weak_topics')
    op.drop_index(op.f('ix_user_weak_topics_topic_id'), table_name='user_weak_topics')
    op.drop_index(op.f('ix_user_weak_topics_last_updated'), table_name='user_weak_topics')
    op.drop_index('idx_user_weakness', table_name='user_weak_topics')
    op.drop_table('user_weak_topics')
    # ### end Alembic commands ###
