"""minor fix in the base question schema

Revision ID: 83f9130f3482
Revises: 0fca6566851e
Create Date: 2025-12-15 15:55:11.909911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83f9130f3482'
down_revision: Union[str, None] = '0fca6566851e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('question', 'mcq_correct_option',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="mcq_correct_option::text::json")
    op.alter_column('question', 'scq_correct_options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="NULLIF(scq_correct_options::text, 'null')::integer")
    op.alter_column('subject', 'exam_type',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject', 'exam_type',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('question', 'scq_correct_options',
               existing_type=sa.Integer(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('question', 'mcq_correct_option',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
