"""fix in the doubt schema

Revision ID: 86c7206d5b07
Revises: 32991d02a8a5
Create Date: 2025-12-22 02:28:32.742047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '86c7206d5b07'
down_revision: Union[str, None] = '32991d02a8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doubt_posts', sa.Column('class_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_index('ix_doubt_posts_class_level', table_name='doubt_posts')
    op.create_index(op.f('ix_doubt_posts_class_id'), 'doubt_posts', ['class_id'], unique=False)
    op.drop_constraint('doubt_posts_class_level_fkey', 'doubt_posts', type_='foreignkey')
    op.create_foreign_key(None, 'doubt_posts', 'class', ['class_id'], ['id'])
    op.drop_column('doubt_posts', 'class_level')
    op.alter_column('users', 'class_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text("'b85e3fc4-41b6-4237-b7b7-0a065d5a1887'::uuid"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'class_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text("'b85e3fc4-41b6-4237-b7b7-0a065d5a1887'::uuid"))
    op.add_column('doubt_posts', sa.Column('class_level', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doubt_posts', type_='foreignkey')
    op.create_foreign_key('doubt_posts_class_level_fkey', 'doubt_posts', 'class', ['class_level'], ['id'])
    op.drop_index(op.f('ix_doubt_posts_class_id'), table_name='doubt_posts')
    op.create_index('ix_doubt_posts_class_level', 'doubt_posts', ['class_level'], unique=False)
    op.drop_column('doubt_posts', 'class_id')
    # ### end Alembic commands ###
