"""youtube videos linked

Revision ID: a1d894779eee
Revises: 623038470b21
Create Date: 2025-12-08 08:16:45.344491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a1d894779eee'
down_revision: Union[str, None] = '623038470b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_videos',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('chapter_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('youtube_video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('youtube_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_videos_chapter_id'), 'youtube_videos', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_youtube_videos_is_active'), 'youtube_videos', ['is_active'], unique=False)
    op.create_index(op.f('ix_youtube_videos_subject_id'), 'youtube_videos', ['subject_id'], unique=False)
    op.add_column('customtest', sa.Column('time_assigned', sa.Integer(), nullable=False))
    op.add_column('customtestanalysis', sa.Column('custom_test_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_index(op.f('ix_customtestanalysis_custom_test_id'), 'customtestanalysis', ['custom_test_id'], unique=False)
    op.create_foreign_key(None, 'customtestanalysis', 'customtest', ['custom_test_id'], ['id'])
    op.add_column('users', sa.Column('avatar_svg', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('current_rating', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('max_rating', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_rating')
    op.drop_column('users', 'current_rating')
    op.drop_column('users', 'avatar_svg')
    op.drop_constraint(None, 'customtestanalysis', type_='foreignkey')
    op.drop_index(op.f('ix_customtestanalysis_custom_test_id'), table_name='customtestanalysis')
    op.drop_column('customtestanalysis', 'custom_test_id')
    op.drop_column('customtest', 'time_assigned')
    op.drop_index(op.f('ix_youtube_videos_subject_id'), table_name='youtube_videos')
    op.drop_index(op.f('ix_youtube_videos_is_active'), table_name='youtube_videos')
    op.drop_index(op.f('ix_youtube_videos_chapter_id'), table_name='youtube_videos')
    op.drop_table('youtube_videos')
    # ### end Alembic commands ###
