"""badge schema fix

Revision ID: b97bef5cc5e1
Revises: 36cda8b7ee71
Create Date: 2025-12-09 16:57:01.800337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b97bef5cc5e1'
down_revision: Union[str, None] = '36cda8b7ee71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_badges_badge_id', table_name='user_badges')
    op.drop_index('ix_user_badges_earned_at', table_name='user_badges')
    op.drop_index('ix_user_badges_is_earned', table_name='user_badges')
    op.drop_index('ix_user_badges_user_id', table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index('ix_badges_badge_type', table_name='badges')
    op.drop_column('badges', 'points_reward')
    op.drop_column('badges', 'rarity')
    op.drop_column('badges', 'badge_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('badge_type', postgresql.ENUM('QUESTIONS_SOLVED', 'ACCURACY', 'DIFFICULTY_MASTER', 'STREAK', 'PERFECT_SCORE', 'SPEED_DEMON', 'CONSISTENCY', 'SUBJECT_MASTER', 'WEEKLY_CHALLENGE', 'MONTHLY_CHALLENGE', name='badgetype'), autoincrement=False, nullable=False))
    op.add_column('badges', sa.Column('rarity', postgresql.ENUM('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY', name='badgerarity'), autoincrement=False, nullable=False))
    op.add_column('badges', sa.Column('points_reward', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_badges_badge_type', 'badges', ['badge_type'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('badge_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('earned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_earned', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], name='user_badges_badge_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_badges_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_badges_pkey')
    )
    op.create_index('ix_user_badges_user_id', 'user_badges', ['user_id'], unique=False)
    op.create_index('ix_user_badges_is_earned', 'user_badges', ['is_earned'], unique=False)
    op.create_index('ix_user_badges_earned_at', 'user_badges', ['earned_at'], unique=False)
    op.create_index('ix_user_badges_badge_id', 'user_badges', ['badge_id'], unique=False)
    # ### end Alembic commands ###
