"""practice arena schema

Revision ID: c20f1ea3e9ef
Revises: 31819dc06595
Create Date: 2025-12-03 19:09:32.387897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c20f1ea3e9ef'
down_revision: Union[str, None] = '31819dc06595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('previous_year_problems',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('exam_detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_previous_year_problems_question_id'), 'previous_year_problems', ['question_id'], unique=False)
    op.create_index(op.f('ix_previous_year_problems_user_id'), 'previous_year_problems', ['user_id'], unique=False)
    op.create_table('question_bookmarked',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bookmarked_created_at'), 'question_bookmarked', ['created_at'], unique=False)
    op.create_index(op.f('ix_question_bookmarked_question_id'), 'question_bookmarked', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_bookmarked_user_id'), 'question_bookmarked', ['user_id'], unique=False)
    op.add_column('question_attempts', sa.Column('hint_used', sa.Boolean(), nullable=False))
    op.alter_column('question_attempts', 'user_answer',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               nullable=True,
               postgresql_using="user_answer::json"
               )
    op.drop_index('ix_question_attempts_attempted_at', table_name='question_attempts')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.create_index('ix_question_attempts_attempted_at', 'question_attempts', ['attempted_at'], unique=False)
    op.alter_column('question_attempts', 'user_answer',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('question_attempts', 'hint_used')
    op.drop_index(op.f('ix_question_bookmarked_user_id'), table_name='question_bookmarked')
    op.drop_index(op.f('ix_question_bookmarked_question_id'), table_name='question_bookmarked')
    op.drop_index(op.f('ix_question_bookmarked_created_at'), table_name='question_bookmarked')
    op.drop_table('question_bookmarked')
    op.drop_index(op.f('ix_previous_year_problems_user_id'), table_name='previous_year_problems')
    op.drop_index(op.f('ix_previous_year_problems_question_id'), table_name='previous_year_problems')
    op.drop_table('previous_year_problems')
    op.drop_table('topic')
    # ### end Alembic commands ###
