"""fix schema

Revision ID: c5625f2ca787
Revises: d8b50e15236c
Create Date: 2025-12-29 14:08:47.299225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5625f2ca787'
down_revision: Union[str, None] = 'd8b50e15236c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treasures',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('chapter_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treasures_chapter_id'), 'treasures', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_treasures_is_active'), 'treasures', ['is_active'], unique=False)
    op.create_index(op.f('ix_treasures_subject_id'), 'treasures', ['subject_id'], unique=False)
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.alter_column('bookmarked_videos', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('bookmarked_videos', 'youtube_video_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('users', 'is_psychometric_completed')
    op.drop_column('users', 'class_grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('class_grade', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_psychometric_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('bookmarked_videos', 'youtube_video_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bookmarked_videos', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), server_default=sa.text("'info'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.drop_index(op.f('ix_treasures_subject_id'), table_name='treasures')
    op.drop_index(op.f('ix_treasures_is_active'), table_name='treasures')
    op.drop_index(op.f('ix_treasures_chapter_id'), table_name='treasures')
    op.drop_table('treasures')
    # ### end Alembic commands ###
