"""minor fix in topics schema

Revision ID: c7a69134c9a6
Revises: c20f1ea3e9ef
Create Date: 2025-12-04 14:38:18.759591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a69134c9a6'
down_revision: Union[str, None] = 'c20f1ea3e9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('topic_chapter_id_fkey', 'topic', type_='foreignkey')
    op.create_foreign_key(None, 'topic', 'chapter', ['chapter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.create_foreign_key('topic_chapter_id_fkey', 'topic', 'subject', ['chapter_id'], ['id'])
    # ### end Alembic commands ###
