"""minor fix

Revision ID: ca18f54541fb
Revises: a1d894779eee
Create Date: 2025-12-08 08:47:22.950073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ca18f54541fb'
down_revision: Union[str, None] = 'a1d894779eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

contest_rank_enum = ENUM(
    'NEWBIE', 'SPECIALIST', 'EXPERT', 'CANDIDATE_MASTER', 'MASTER', 'GRANDMASTER', 'LEGENDARY_GRANDMASTER',
    name='contestrank'
)


def upgrade() -> None:
    """Upgrade schema."""
    contest_rank_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('title', contest_rank_enum, nullable=True))
    op.add_column('youtube_videos', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_videos', 'title')
    op.drop_column('users', 'title')
    contest_rank_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
