"""add badge performance indexes

Revision ID: d7b276c24f65
Revises: 765633b05342
Create Date: 2025-01-15 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd7b276c24f65'
down_revision: Union[str, None] = '765633b05342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Index for badge queries (ordering by created_at)
    op.create_index(
        'ix_badges_created_at',
        'badges',
        ['created_at'],
        unique=False
    )
    
    # Composite index for active badges ordered by created_at
    op.create_index(
        'ix_badges_is_active_created_at',
        'badges',
        ['is_active', 'created_at'],
        unique=False
    )
    
    # Composite index for user_badges lookups (user_id + badge_id)
    op.create_index(
        'ix_user_badges_user_id_badge_id',
        'user_badges',
        ['user_id', 'badge_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_badges_user_id_badge_id', table_name='user_badges')
    op.drop_index('ix_badges_is_active_created_at', table_name='badges')
    op.drop_index('ix_badges_created_at', table_name='badges')
    # ### end Alembic commands ###

