"""minor changes in the schema

Revision ID: d8b50e15236c
Revises: 3731219cfe79
Create Date: 2025-12-24 00:28:16.344713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b50e15236c'
down_revision: Union[str, None] = '3731219cfe79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone_offset', sa.Integer(),server_default=sa.text("330") ,nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone_offset')
    # ### end Alembic commands ###
