"""minor fix in the classes api

Revision ID: e54d602220c1
Revises: 75de33638e92
Create Date: 2025-12-21 23:30:15.860855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e54d602220c1'
down_revision: Union[str, None] = '75de33638e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), server_default="UNKNOWN", nullable=False))
    op.drop_column('class', 'class_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('class_level', postgresql.ENUM('Ninth', 'Tenth', 'Eleventh', 'Twelth', name='class_level'), autoincrement=False, nullable=False))
    op.drop_column('class', 'name')
    # ### end Alembic commands ###
