"""add total_time to contest_leaderboard

Revision ID: f92f03a18586
Revises: 23cf9484a9ae
Create Date: 2025-01-15 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f92f03a18586'
down_revision: Union[str, None] = '23cf9484a9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contestleaderboard', sa.Column('total_time', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contestleaderboard', 'total_time')
    # ### end Alembic commands ###

